language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - composer install

script:
  - vendor/bin/parallel-lint --exclude vendor .

before_deploy: "zip -r 'el_playamatrix_importer' el_playamatrix_importer"
