<?php

require_once('libraries/autoload.php');
use PlayaMatrixImporter\Converters\PlayaConverter;

class PlayaConverterTest extends \PHPUnit_Framework_TestCase {

	/**
	 * Test PlayaConverter::convertSettings() method
	 *
	 * @dataProvider settingsDataProvider
	 */
	public function testSettingsConversion($expected, $settings, $description)
	{
		$new_settings = PlayaConverter::convertSettings($settings);
		$this->assertEquals($expected, $new_settings, $description);
	}

	public function settingsDataProvider()
	{
		$return = array();

		$playa_settings = array();

		$expected = array(
			'channels'			=> array(),
			'categories'		=> array(),
			'authors'			=> array(),
			'statuses'			=> array(),
			'allow_multiple'	=> FALSE,
			'expired'			=> FALSE,
			'future'			=> TRUE,
			'order_field'		=> 'title',
			'order_dir'			=> 'asc',
			'limit'				=> 0,
		);

		$return[] = array($expected, $playa_settings, 'Test empty array');

		$playa_settings = array(
			'ui_mode' => 'drop',
			'blogs' => array('1', '2')
		);

		$expected['channels'] = array(1, 2);
		$expected['allow_multiple'] = TRUE;

		$return[] = array($expected, $playa_settings, 'Test older-style, partial settings - multi relationship');

		$playa_settings = array(
			'ui_mode' => 'select',
			'blogs' => array('2')
		);

		$expected['channels'] = array(2);
		$expected['allow_multiple'] = FALSE;

		$return[] = array($expected, $playa_settings, 'Test older-style, partial settings - single relationship');

		$playa_settings = array(
			'multi' => 'y',
			'expired' => 'n',
			'future' => 'y',
			'editable' => 'n',
			'channels' => array('2'),
			'orderby' => 'title',
			'sort' => 'ASC',
			'field_show_smileys' => 'n',
			'field_show_glossary' => 'n',
			'field_show_spellcheck' => 'n',
			'field_show_formatting_btns' => 'n',
			'field_show_file_selector' => 'n',
			'field_show_writemode' => 'n'
		);

		$expected['allow_multiple'] = TRUE;

		$return[] = array($expected, $playa_settings, 'Test newer-style, partial settings');

		$playa_settings['multi'] = 'n';
		$playa_settings['expired'] = 'y';
		$playa_settings['future'] = 'n';
		$playa_settings['editable'] = 'n';
		$playa_settings['channels'] = array('any');
		$playa_settings['orderby'] = 'entry_date';
		$playa_settings['sort'] = 'DESC';
		$playa_settings['limit'] = 100;

		$expected['allow_multiple'] = FALSE;
		$expected['expired'] = TRUE;
		$expected['future'] = FALSE;
		$expected['channels'] = array();
		$expected['order_field'] = 'entry_date';
		$expected['order_dir'] = 'desc';
		$expected['limit'] = 100;

		$return[] = array($expected, $playa_settings, 'Test various settings values');

		$playa_settings['orderby'] = 'lalalala';
		$playa_settings['sort'] = 'hahahah';
		$playa_settings['limit'] = 'roflrofl';

		$expected['order_field'] = 'title';
		$expected['order_dir'] = 'asc';
		$expected['limit'] = 0;

		$return[] = array($expected, $playa_settings, 'Test garbage values');

		return $return;
	}

	/**
	 * Test PlayaConverter::convertPlayaRelationships() method
	 *
	 * @dataProvider relationshipsDataProvider
	 */
	public function testDataConversion($expected, $data, $field_id, $description)
	{
		$new_data = PlayaConverter::convertPlayaRelationships($data, $field_id);
		$this->assertEquals($expected, $new_data, $description);
	}

	public function relationshipsDataProvider()
	{
		$return = array();

		$data = array(
			0 => array(
				'rel_id' => '2058',
				'parent_entry_id' => '394',
				'parent_field_id' => '40',
				'parent_col_id' => NULL,
				'parent_row_id' => NULL,
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '278',
				'rel_order' => '1',
			) ,
			1 => array(
				'rel_id' => '2057',
				'parent_entry_id' => '394',
				'parent_field_id' => '40',
				'parent_col_id' => NULL,
				'parent_row_id' => NULL,
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '245',
				'rel_order' => '0',
			) ,
			2 => array(
				'rel_id' => '786',
				'parent_entry_id' => '410',
				'parent_field_id' => '40',
				'parent_col_id' => NULL,
				'parent_row_id' => NULL,
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '349',
				'rel_order' => '1',
			) ,
			3 => array(
				'rel_id' => '785',
				'parent_entry_id' => '410',
				'parent_field_id' => '40',
				'parent_col_id' => NULL,
				'parent_row_id' => NULL,
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '315',
				'rel_order' => '0',
			)
		);
		$expected = array(
			0 => array(
				'parent_id' => '394',
				'field_id' => 120,
				'child_id' => '278',
				'order' => '1',
			) ,
			1 => array(
				'parent_id' => '394',
				'field_id' => 120,
				'child_id' => '245',
				'order' => '0',
			) ,
			2 => array(
				'parent_id' => '410',
				'field_id' => 120,
				'child_id' => '349',
				'order' => '1',
			) ,
			3 => array(
				'parent_id' => '410',
				'field_id' => 120,
				'child_id' => '315',
				'order' => '0',
			)
		);
		$return[] = array($expected, $data, 120, 'Sample data');

		return $return;
	}

	/**
	 * Test PlayaConverter::convertPlayaRelationshipsForGrid() method
	 *
	 * @dataProvider gridRelationshipsDataProvider
	 */
	public function testGridDataConversion($expected, $data, $matrix_to_grid_fields, $matrix_to_grid_cols, $description)
	{
		$new_data = PlayaConverter::convertPlayaRelationshipsForGrid($data, $matrix_to_grid_fields, $matrix_to_grid_cols);
		$this->assertEquals($expected, $new_data, $description);
	}

	public function gridRelationshipsDataProvider()
	{
		$return = array();

		$matrix_to_grid_fields = array(
			13 => 123,
			29 => 124,
			32 => 125,
			36 => 126,
			41 => 127,
			49 => 128,
			50 => 129,
			52 => 130,
			54 => 131,
			59 => 132,
			61 => 133,
			60 => 134,
			69 => 135,
			70 => 136,
			71 => 137,
			88 => 138,
			85 => 139,
			86 => 140,
			92 => 141,
			95 => 142,
			98 => 143,
			99 => 144,
			118 => 145,
			119 => 146
		);
		$matrix_to_grid_cols = array(
			1 => 15,
			2 => 16,
			3 => 17,
			4 => 18,
			5 => 19,
			6 => 20,
			46 => 21,
			8 => 22,
			9 => 23,
			36 => 24,
			10 => 25,
			11 => 26,
			12 => 27,
			13 => 28,
			14 => 29,
			15 => 30,
			16 => 31,
			17 => 32,
			18 => 33,
			19 => 34,
			20 => 35,
			21 => 36,
			22 => 37,
			23 => 38,
			24 => 39,
			25 => 40,
			26 => 41,
			27 => 42,
			28 => 43,
			29 => 44,
			30 => 45,
			31 => 46,
			32 => 47,
			33 => 48,
			34 => 49,
			35 => 50,
			37 => 51,
			42 => 52,
			43 => 53,
			38 => 54,
			39 => 55,
			40 => 56,
			41 => 57,
			45 => 58,
			47 => 59,
			48 => 60,
			49 => 61,
			50 => 62,
			51 => 63,
			52 => 64,
			53 => 65,
			54 => 66,
			55 => 67,
			56 => 68,
			57 => 69,
			58 => 70,
			59 => 71,
			60 => 72,
			61 => 73
		);
		$data = array(
			0 => array(
				'rel_id' => '2953',
				'parent_entry_id' => '800',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '2210',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1200',
				'rel_order' => '0',
			) ,
			1 => array(
				'rel_id' => '2952',
				'parent_entry_id' => '800',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '2209',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1199',
				'rel_order' => '0',
			) ,
			2 => array(
				'rel_id' => '2951',
				'parent_entry_id' => '800',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '2202',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1198',
				'rel_order' => '0',
			) ,
			3 => array(
				'rel_id' => '2950',
				'parent_entry_id' => '800',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '2201',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1197',
				'rel_order' => '0',
			) ,
			4 => array(
				'rel_id' => '2949',
				'parent_entry_id' => '800',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '2200',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1196',
				'rel_order' => '0',
			) ,
			5 => array(
				'rel_id' => '2948',
				'parent_entry_id' => '800',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '2199',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1195',
				'rel_order' => '0',
			) ,
			6 => array(
				'rel_id' => '2947',
				'parent_entry_id' => '800',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '2171',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1194',
				'rel_order' => '0',
			) ,
			7 => array(
				'rel_id' => '2946',
				'parent_entry_id' => '800',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '2170',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1192',
				'rel_order' => '0',
			) ,
			8 => array(
				'rel_id' => '2945',
				'parent_entry_id' => '800',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '2176',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1183',
				'rel_order' => '0',
			) ,
			9 => array(
				'rel_id' => '2944',
				'parent_entry_id' => '800',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '2169',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1182',
				'rel_order' => '0',
			) ,
			10 => array(
				'rel_id' => '2943',
				'parent_entry_id' => '800',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '2168',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1177',
				'rel_order' => '0',
			) ,
			11 => array(
				'rel_id' => '2844',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '2160',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1169',
				'rel_order' => '0',
			) ,
			12 => array(
				'rel_id' => '2842',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '2159',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1168',
				'rel_order' => '0',
			) ,
			13 => array(
				'rel_id' => '2839',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '2158',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1167',
				'rel_order' => '0',
			) ,
			14 => array(
				'rel_id' => '2834',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '802',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '556',
				'rel_order' => '0',
			) ,
			15 => array(
				'rel_id' => '2835',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '803',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '557',
				'rel_order' => '0',
			) ,
			16 => array(
				'rel_id' => '2836',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '804',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '558',
				'rel_order' => '0',
			) ,
			17 => array(
				'rel_id' => '2837',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '805',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '559',
				'rel_order' => '0',
			) ,
			18 => array(
				'rel_id' => '2838',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '806',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '564',
				'rel_order' => '0',
			) ,
			19 => array(
				'rel_id' => '2840',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '807',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '567',
				'rel_order' => '0',
			) ,
			20 => array(
				'rel_id' => '2841',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '808',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '565',
				'rel_order' => '0',
			) ,
			21 => array(
				'rel_id' => '2843',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '809',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '566',
				'rel_order' => '0',
			) ,
			22 => array(
				'rel_id' => '2845',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '810',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '568',
				'rel_order' => '0',
			) ,
			23 => array(
				'rel_id' => '2846',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '811',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '573',
				'rel_order' => '0',
			) ,
			24 => array(
				'rel_id' => '2847',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '812',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '574',
				'rel_order' => '0',
			) ,
			25 => array(
				'rel_id' => '2848',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '813',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '575',
				'rel_order' => '0',
			) ,
			26 => array(
				'rel_id' => '2849',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '814',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '580',
				'rel_order' => '0',
			) ,
			27 => array(
				'rel_id' => '2850',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '815',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '597',
				'rel_order' => '0',
			) ,
			28 => array(
				'rel_id' => '2851',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '816',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '598',
				'rel_order' => '0',
			) ,
			29 => array(
				'rel_id' => '2852',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '817',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '599',
				'rel_order' => '0',
			) ,
			30 => array(
				'rel_id' => '2853',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '818',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '600',
				'rel_order' => '0',
			) ,
			31 => array(
				'rel_id' => '2854',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '819',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '584',
				'rel_order' => '0',
			) ,
			32 => array(
				'rel_id' => '2855',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '820',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '585',
				'rel_order' => '0',
			) ,
			33 => array(
				'rel_id' => '2856',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '821',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '586',
				'rel_order' => '0',
			) ,
			34 => array(
				'rel_id' => '2857',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '822',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '587',
				'rel_order' => '0',
			) ,
			35 => array(
				'rel_id' => '2858',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '823',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '589',
				'rel_order' => '0',
			) ,
			36 => array(
				'rel_id' => '2859',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '824',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '588',
				'rel_order' => '0',
			) ,
			37 => array(
				'rel_id' => '2860',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '825',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '601',
				'rel_order' => '0',
			) ,
			38 => array(
				'rel_id' => '2861',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '826',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '604',
				'rel_order' => '0',
			) ,
			39 => array(
				'rel_id' => '2862',
				'parent_entry_id' => '560',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '827',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '603',
				'rel_order' => '0',
			) ,
			40 => array(
				'rel_id' => '390',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '776',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '527',
				'rel_order' => '0',
			) ,
			41 => array(
				'rel_id' => '391',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '778',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '528',
				'rel_order' => '0',
			) ,
			42 => array(
				'rel_id' => '392',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '779',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '529',
				'rel_order' => '0',
			) ,
			43 => array(
				'rel_id' => '393',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '780',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '530',
				'rel_order' => '0',
			) ,
			44 => array(
				'rel_id' => '394',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '782',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '535',
				'rel_order' => '0',
			) ,
			45 => array(
				'rel_id' => '395',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '783',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '536',
				'rel_order' => '0',
			) ,
			46 => array(
				'rel_id' => '396',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '784',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '537',
				'rel_order' => '0',
			) ,
			47 => array(
				'rel_id' => '397',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '786',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '538',
				'rel_order' => '0',
			) ,
			48 => array(
				'rel_id' => '398',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '787',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '539',
				'rel_order' => '0',
			) ,
			49 => array(
				'rel_id' => '399',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '789',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '540',
				'rel_order' => '0',
			) ,
			50 => array(
				'rel_id' => '400',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '791',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '531',
				'rel_order' => '0',
			) ,
			51 => array(
				'rel_id' => '401',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '792',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '532',
				'rel_order' => '0',
			) ,
			52 => array(
				'rel_id' => '402',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '793',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '534',
				'rel_order' => '0',
			) ,
			53 => array(
				'rel_id' => '403',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '794',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '546',
				'rel_order' => '0',
			) ,
			54 => array(
				'rel_id' => '404',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '795',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '541',
				'rel_order' => '0',
			) ,
			55 => array(
				'rel_id' => '405',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '796',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '542',
				'rel_order' => '0',
			) ,
			56 => array(
				'rel_id' => '406',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '797',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '543',
				'rel_order' => '0',
			) ,
			57 => array(
				'rel_id' => '407',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '798',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '547',
				'rel_order' => '0',
			) ,
			58 => array(
				'rel_id' => '408',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '799',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '544',
				'rel_order' => '0',
			) ,
			59 => array(
				'rel_id' => '409',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '800',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '545',
				'rel_order' => '0',
			) ,
			60 => array(
				'rel_id' => '410',
				'parent_entry_id' => '533',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '801',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '548',
				'rel_order' => '0',
			) ,
			61 => array(
				'rel_id' => '411',
				'parent_entry_id' => '523',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '773',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '521',
				'rel_order' => '0',
			) ,
			62 => array(
				'rel_id' => '412',
				'parent_entry_id' => '523',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '774',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '522',
				'rel_order' => '0',
			) ,
			63 => array(
				'rel_id' => '413',
				'parent_entry_id' => '523',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '775',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '524',
				'rel_order' => '0',
			) ,
			64 => array(
				'rel_id' => '414',
				'parent_entry_id' => '502',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '763',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '492',
				'rel_order' => '0',
			) ,
			65 => array(
				'rel_id' => '415',
				'parent_entry_id' => '502',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '764',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '493',
				'rel_order' => '0',
			) ,
			66 => array(
				'rel_id' => '416',
				'parent_entry_id' => '502',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '765',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '494',
				'rel_order' => '0',
			) ,
			67 => array(
				'rel_id' => '417',
				'parent_entry_id' => '502',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '766',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '495',
				'rel_order' => '0',
			) ,
			68 => array(
				'rel_id' => '418',
				'parent_entry_id' => '502',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '767',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '496',
				'rel_order' => '0',
			) ,
			69 => array(
				'rel_id' => '419',
				'parent_entry_id' => '502',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '768',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '497',
				'rel_order' => '0',
			) ,
			70 => array(
				'rel_id' => '420',
				'parent_entry_id' => '502',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '769',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '498',
				'rel_order' => '0',
			) ,
			71 => array(
				'rel_id' => '421',
				'parent_entry_id' => '502',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '770',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '499',
				'rel_order' => '0',
			) ,
			72 => array(
				'rel_id' => '422',
				'parent_entry_id' => '502',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '771',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '500',
				'rel_order' => '0',
			) ,
			73 => array(
				'rel_id' => '423',
				'parent_entry_id' => '502',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '772',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '501',
				'rel_order' => '0',
			) ,
			74 => array(
				'rel_id' => '424',
				'parent_entry_id' => '491',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '748',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '480',
				'rel_order' => '0',
			) ,
			75 => array(
				'rel_id' => '425',
				'parent_entry_id' => '491',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '749',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '481',
				'rel_order' => '0',
			) ,
			76 => array(
				'rel_id' => '426',
				'parent_entry_id' => '491',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '750',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '479',
				'rel_order' => '0',
			) ,
			77 => array(
				'rel_id' => '427',
				'parent_entry_id' => '491',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '752',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '482',
				'rel_order' => '0',
			) ,
			78 => array(
				'rel_id' => '428',
				'parent_entry_id' => '491',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '753',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '483',
				'rel_order' => '0',
			) ,
			79 => array(
				'rel_id' => '429',
				'parent_entry_id' => '491',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '754',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '484',
				'rel_order' => '0',
			) ,
			80 => array(
				'rel_id' => '430',
				'parent_entry_id' => '491',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '755',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '478',
				'rel_order' => '0',
			) ,
			81 => array(
				'rel_id' => '431',
				'parent_entry_id' => '491',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '756',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '485',
				'rel_order' => '0',
			) ,
			82 => array(
				'rel_id' => '432',
				'parent_entry_id' => '491',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '757',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '486',
				'rel_order' => '0',
			) ,
			83 => array(
				'rel_id' => '433',
				'parent_entry_id' => '491',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '758',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '513',
				'rel_order' => '0',
			) ,
			84 => array(
				'rel_id' => '434',
				'parent_entry_id' => '491',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '759',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '487',
				'rel_order' => '0',
			) ,
			85 => array(
				'rel_id' => '435',
				'parent_entry_id' => '491',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '760',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '488',
				'rel_order' => '0',
			) ,
			86 => array(
				'rel_id' => '436',
				'parent_entry_id' => '491',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '761',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '489',
				'rel_order' => '0',
			) ,
			87 => array(
				'rel_id' => '437',
				'parent_entry_id' => '491',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '762',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '490',
				'rel_order' => '0',
			) ,
			88 => array(
				'rel_id' => '2954',
				'parent_entry_id' => '476',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '739',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '469',
				'rel_order' => '0',
			) ,
			89 => array(
				'rel_id' => '2955',
				'parent_entry_id' => '476',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '740',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '470',
				'rel_order' => '0',
			) ,
			90 => array(
				'rel_id' => '2956',
				'parent_entry_id' => '476',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '741',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '471',
				'rel_order' => '0',
			) ,
			91 => array(
				'rel_id' => '2957',
				'parent_entry_id' => '476',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '742',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '477',
				'rel_order' => '0',
			) ,
			92 => array(
				'rel_id' => '2958',
				'parent_entry_id' => '476',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '743',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '472',
				'rel_order' => '0',
			) ,
			93 => array(
				'rel_id' => '2959',
				'parent_entry_id' => '476',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '744',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '473',
				'rel_order' => '0',
			) ,
			94 => array(
				'rel_id' => '2960',
				'parent_entry_id' => '476',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '745',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '474',
				'rel_order' => '0',
			) ,
			95 => array(
				'rel_id' => '2961',
				'parent_entry_id' => '476',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '746',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '512',
				'rel_order' => '0',
			) ,
			96 => array(
				'rel_id' => '2962',
				'parent_entry_id' => '476',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '747',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '475',
				'rel_order' => '0',
			) ,
			97 => array(
				'rel_id' => '2700',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '716',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '456',
				'rel_order' => '0',
			) ,
			98 => array(
				'rel_id' => '2701',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '717',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '457',
				'rel_order' => '0',
			) ,
			99 => array(
				'rel_id' => '2702',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '718',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '503',
				'rel_order' => '0',
			) ,
			100 => array(
				'rel_id' => '2703',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '719',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '504',
				'rel_order' => '0',
			) ,
			101 => array(
				'rel_id' => '2704',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '720',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '505',
				'rel_order' => '0',
			) ,
			102 => array(
				'rel_id' => '2705',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '722',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '458',
				'rel_order' => '0',
			) ,
			103 => array(
				'rel_id' => '2706',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '723',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '506',
				'rel_order' => '0',
			) ,
			104 => array(
				'rel_id' => '2707',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '724',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '459',
				'rel_order' => '0',
			) ,
			105 => array(
				'rel_id' => '2708',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '725',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '507',
				'rel_order' => '0',
			) ,
			106 => array(
				'rel_id' => '2709',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '726',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '460',
				'rel_order' => '0',
			) ,
			107 => array(
				'rel_id' => '2710',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '727',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '668',
				'rel_order' => '0',
			) ,
			108 => array(
				'rel_id' => '2711',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '728',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '461',
				'rel_order' => '0',
			) ,
			109 => array(
				'rel_id' => '2712',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '730',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '462',
				'rel_order' => '0',
			) ,
			110 => array(
				'rel_id' => '2713',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '731',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '463',
				'rel_order' => '0',
			) ,
			111 => array(
				'rel_id' => '2714',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '732',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '508',
				'rel_order' => '0',
			) ,
			112 => array(
				'rel_id' => '2715',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '733',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '511',
				'rel_order' => '0',
			) ,
			113 => array(
				'rel_id' => '2716',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '734',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '464',
				'rel_order' => '0',
			) ,
			114 => array(
				'rel_id' => '2717',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '735',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '465',
				'rel_order' => '0',
			) ,
			115 => array(
				'rel_id' => '2718',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '736',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '509',
				'rel_order' => '0',
			) ,
			116 => array(
				'rel_id' => '2719',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '737',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '466',
				'rel_order' => '0',
			) ,
			117 => array(
				'rel_id' => '2720',
				'parent_entry_id' => '467',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '738',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '510',
				'rel_order' => '0',
			) ,
			118 => array(
				'rel_id' => '2645',
				'parent_entry_id' => '650',
				'parent_field_id' => '69',
				'parent_col_id' => '28',
				'parent_row_id' => '1025',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '329',
				'rel_order' => '0',
			) ,
			119 => array(
				'rel_id' => '2646',
				'parent_entry_id' => '650',
				'parent_field_id' => '69',
				'parent_col_id' => '28',
				'parent_row_id' => '1026',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '241',
				'rel_order' => '0',
			) ,
			120 => array(
				'rel_id' => '2647',
				'parent_entry_id' => '650',
				'parent_field_id' => '69',
				'parent_col_id' => '28',
				'parent_row_id' => '1027',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '315',
				'rel_order' => '0',
			) ,
			121 => array(
				'rel_id' => '2648',
				'parent_entry_id' => '650',
				'parent_field_id' => '69',
				'parent_col_id' => '28',
				'parent_row_id' => '1028',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '332',
				'rel_order' => '0',
			) ,
			122 => array(
				'rel_id' => '2649',
				'parent_entry_id' => '650',
				'parent_field_id' => '69',
				'parent_col_id' => '28',
				'parent_row_id' => '1029',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '304',
				'rel_order' => '0',
			) ,
			123 => array(
				'rel_id' => '2650',
				'parent_entry_id' => '650',
				'parent_field_id' => '69',
				'parent_col_id' => '28',
				'parent_row_id' => '1030',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '244',
				'rel_order' => '0',
			) ,
			124 => array(
				'rel_id' => '2651',
				'parent_entry_id' => '650',
				'parent_field_id' => '69',
				'parent_col_id' => '28',
				'parent_row_id' => '1031',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '297',
				'rel_order' => '0',
			) ,
			125 => array(
				'rel_id' => '2652',
				'parent_entry_id' => '650',
				'parent_field_id' => '69',
				'parent_col_id' => '28',
				'parent_row_id' => '1032',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '235',
				'rel_order' => '0',
			) ,
			126 => array(
				'rel_id' => '2653',
				'parent_entry_id' => '650',
				'parent_field_id' => '69',
				'parent_col_id' => '28',
				'parent_row_id' => '1033',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '652',
				'rel_order' => '0',
			) ,
			127 => array(
				'rel_id' => '2654',
				'parent_entry_id' => '650',
				'parent_field_id' => '69',
				'parent_col_id' => '28',
				'parent_row_id' => '1034',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '654',
				'rel_order' => '0',
			) ,
			128 => array(
				'rel_id' => '2655',
				'parent_entry_id' => '650',
				'parent_field_id' => '69',
				'parent_col_id' => '28',
				'parent_row_id' => '1035',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '656',
				'rel_order' => '0',
			) ,
			129 => array(
				'rel_id' => '2656',
				'parent_entry_id' => '650',
				'parent_field_id' => '69',
				'parent_col_id' => '28',
				'parent_row_id' => '1036',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '288',
				'rel_order' => '0',
			) ,
			130 => array(
				'rel_id' => '2941',
				'parent_entry_id' => '800',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '1258',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1175',
				'rel_order' => '0',
			) ,
			131 => array(
				'rel_id' => '2942',
				'parent_entry_id' => '800',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '1262',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1176',
				'rel_order' => '0',
			) ,
			132 => array(
				'rel_id' => '2098',
				'parent_entry_id' => '1021',
				'parent_field_id' => '61',
				'parent_col_id' => '23',
				'parent_row_id' => '1867',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '1022',
				'rel_order' => '0',
			) ,
			133 => array(
				'rel_id' => '2963',
				'parent_entry_id' => '359',
				'parent_field_id' => '119',
				'parent_col_id' => '61',
				'parent_row_id' => '2212',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '654',
				'rel_order' => '0',
			) ,
			134 => array(
				'rel_id' => '2964',
				'parent_entry_id' => '359',
				'parent_field_id' => '119',
				'parent_col_id' => '61',
				'parent_row_id' => '2212',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '626',
				'rel_order' => '1',
			) ,
			135 => array(
				'rel_id' => '2965',
				'parent_entry_id' => '359',
				'parent_field_id' => '119',
				'parent_col_id' => '61',
				'parent_row_id' => '2212',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '656',
				'rel_order' => '2',
			) ,
			136 => array(
				'rel_id' => '2966',
				'parent_entry_id' => '359',
				'parent_field_id' => '119',
				'parent_col_id' => '61',
				'parent_row_id' => '2213',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '770',
				'rel_order' => '0',
			) ,
			137 => array(
				'rel_id' => '2967',
				'parent_entry_id' => '359',
				'parent_field_id' => '119',
				'parent_col_id' => '61',
				'parent_row_id' => '2213',
				'parent_var_id' => NULL,
				'parent_is_draft' => '0',
				'child_entry_id' => '628',
				'rel_order' => '1',
			)
		);
		$expected = array(
			0 => array(
				'parent_id' => '800',
				'field_id' => 38,
				'child_id' => '1200',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '2210',
			) ,
			1 => array(
				'parent_id' => '800',
				'field_id' => 38,
				'child_id' => '1199',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '2209',
			) ,
			2 => array(
				'parent_id' => '800',
				'field_id' => 38,
				'child_id' => '1198',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '2202',
			) ,
			3 => array(
				'parent_id' => '800',
				'field_id' => 38,
				'child_id' => '1197',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '2201',
			) ,
			4 => array(
				'parent_id' => '800',
				'field_id' => 38,
				'child_id' => '1196',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '2200',
			) ,
			5 => array(
				'parent_id' => '800',
				'field_id' => 38,
				'child_id' => '1195',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '2199',
			) ,
			6 => array(
				'parent_id' => '800',
				'field_id' => 38,
				'child_id' => '1194',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '2171',
			) ,
			7 => array(
				'parent_id' => '800',
				'field_id' => 38,
				'child_id' => '1192',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '2170',
			) ,
			8 => array(
				'parent_id' => '800',
				'field_id' => 38,
				'child_id' => '1183',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '2176',
			) ,
			9 => array(
				'parent_id' => '800',
				'field_id' => 38,
				'child_id' => '1182',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '2169',
			) ,
			10 => array(
				'parent_id' => '800',
				'field_id' => 38,
				'child_id' => '1177',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '2168',
			) ,
			11 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '1169',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '2160',
			) ,
			12 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '1168',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '2159',
			) ,
			13 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '1167',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '2158',
			) ,
			14 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '556',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '802',
			) ,
			15 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '557',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '803',
			) ,
			16 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '558',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '804',
			) ,
			17 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '559',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '805',
			) ,
			18 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '564',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '806',
			) ,
			19 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '567',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '807',
			) ,
			20 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '565',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '808',
			) ,
			21 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '566',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '809',
			) ,
			22 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '568',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '810',
			) ,
			23 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '573',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '811',
			) ,
			24 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '574',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '812',
			) ,
			25 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '575',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '813',
			) ,
			26 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '580',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '814',
			) ,
			27 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '597',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '815',
			) ,
			28 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '598',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '816',
			) ,
			29 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '599',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '817',
			) ,
			30 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '600',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '818',
			) ,
			31 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '584',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '819',
			) ,
			32 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '585',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '820',
			) ,
			33 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '586',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '821',
			) ,
			34 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '587',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '822',
			) ,
			35 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '589',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '823',
			) ,
			36 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '588',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '824',
			) ,
			37 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '601',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '825',
			) ,
			38 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '604',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '826',
			) ,
			39 => array(
				'parent_id' => '560',
				'field_id' => 38,
				'child_id' => '603',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '827',
			) ,
			40 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '527',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '776',
			) ,
			41 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '528',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '778',
			) ,
			42 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '529',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '779',
			) ,
			43 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '530',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '780',
			) ,
			44 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '535',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '782',
			) ,
			45 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '536',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '783',
			) ,
			46 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '537',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '784',
			) ,
			47 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '538',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '786',
			) ,
			48 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '539',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '787',
			) ,
			49 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '540',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '789',
			) ,
			50 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '531',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '791',
			) ,
			51 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '532',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '792',
			) ,
			52 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '534',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '793',
			) ,
			53 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '546',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '794',
			) ,
			54 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '541',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '795',
			) ,
			55 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '542',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '796',
			) ,
			56 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '543',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '797',
			) ,
			57 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '547',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '798',
			) ,
			58 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '544',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '799',
			) ,
			59 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '545',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '800',
			) ,
			60 => array(
				'parent_id' => '533',
				'field_id' => 38,
				'child_id' => '548',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '801',
			) ,
			61 => array(
				'parent_id' => '523',
				'field_id' => 38,
				'child_id' => '521',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '773',
			) ,
			62 => array(
				'parent_id' => '523',
				'field_id' => 38,
				'child_id' => '522',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '774',
			) ,
			63 => array(
				'parent_id' => '523',
				'field_id' => 38,
				'child_id' => '524',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '775',
			) ,
			64 => array(
				'parent_id' => '502',
				'field_id' => 38,
				'child_id' => '492',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '763',
			) ,
			65 => array(
				'parent_id' => '502',
				'field_id' => 38,
				'child_id' => '493',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '764',
			) ,
			66 => array(
				'parent_id' => '502',
				'field_id' => 38,
				'child_id' => '494',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '765',
			) ,
			67 => array(
				'parent_id' => '502',
				'field_id' => 38,
				'child_id' => '495',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '766',
			) ,
			68 => array(
				'parent_id' => '502',
				'field_id' => 38,
				'child_id' => '496',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '767',
			) ,
			69 => array(
				'parent_id' => '502',
				'field_id' => 38,
				'child_id' => '497',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '768',
			) ,
			70 => array(
				'parent_id' => '502',
				'field_id' => 38,
				'child_id' => '498',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '769',
			) ,
			71 => array(
				'parent_id' => '502',
				'field_id' => 38,
				'child_id' => '499',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '770',
			) ,
			72 => array(
				'parent_id' => '502',
				'field_id' => 38,
				'child_id' => '500',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '771',
			) ,
			73 => array(
				'parent_id' => '502',
				'field_id' => 38,
				'child_id' => '501',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '772',
			) ,
			74 => array(
				'parent_id' => '491',
				'field_id' => 38,
				'child_id' => '480',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '748',
			) ,
			75 => array(
				'parent_id' => '491',
				'field_id' => 38,
				'child_id' => '481',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '749',
			) ,
			76 => array(
				'parent_id' => '491',
				'field_id' => 38,
				'child_id' => '479',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '750',
			) ,
			77 => array(
				'parent_id' => '491',
				'field_id' => 38,
				'child_id' => '482',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '752',
			) ,
			78 => array(
				'parent_id' => '491',
				'field_id' => 38,
				'child_id' => '483',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '753',
			) ,
			79 => array(
				'parent_id' => '491',
				'field_id' => 38,
				'child_id' => '484',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '754',
			) ,
			80 => array(
				'parent_id' => '491',
				'field_id' => 38,
				'child_id' => '478',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '755',
			) ,
			81 => array(
				'parent_id' => '491',
				'field_id' => 38,
				'child_id' => '485',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '756',
			) ,
			82 => array(
				'parent_id' => '491',
				'field_id' => 38,
				'child_id' => '486',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '757',
			) ,
			83 => array(
				'parent_id' => '491',
				'field_id' => 38,
				'child_id' => '513',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '758',
			) ,
			84 => array(
				'parent_id' => '491',
				'field_id' => 38,
				'child_id' => '487',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '759',
			) ,
			85 => array(
				'parent_id' => '491',
				'field_id' => 38,
				'child_id' => '488',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '760',
			) ,
			86 => array(
				'parent_id' => '491',
				'field_id' => 38,
				'child_id' => '489',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '761',
			) ,
			87 => array(
				'parent_id' => '491',
				'field_id' => 38,
				'child_id' => '490',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '762',
			) ,
			88 => array(
				'parent_id' => '476',
				'field_id' => 38,
				'child_id' => '469',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '739',
			) ,
			89 => array(
				'parent_id' => '476',
				'field_id' => 38,
				'child_id' => '470',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '740',
			) ,
			90 => array(
				'parent_id' => '476',
				'field_id' => 38,
				'child_id' => '471',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '741',
			) ,
			91 => array(
				'parent_id' => '476',
				'field_id' => 38,
				'child_id' => '477',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '742',
			) ,
			92 => array(
				'parent_id' => '476',
				'field_id' => 38,
				'child_id' => '472',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '743',
			) ,
			93 => array(
				'parent_id' => '476',
				'field_id' => 38,
				'child_id' => '473',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '744',
			) ,
			94 => array(
				'parent_id' => '476',
				'field_id' => 38,
				'child_id' => '474',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '745',
			) ,
			95 => array(
				'parent_id' => '476',
				'field_id' => 38,
				'child_id' => '512',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '746',
			) ,
			96 => array(
				'parent_id' => '476',
				'field_id' => 38,
				'child_id' => '475',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '747',
			) ,
			97 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '456',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '716',
			) ,
			98 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '457',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '717',
			) ,
			99 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '503',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '718',
			) ,
			100 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '504',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '719',
			) ,
			101 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '505',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '720',
			) ,
			102 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '458',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '722',
			) ,
			103 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '506',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '723',
			) ,
			104 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '459',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '724',
			) ,
			105 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '507',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '725',
			) ,
			106 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '460',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '726',
			) ,
			107 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '668',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '727',
			) ,
			108 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '461',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '728',
			) ,
			109 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '462',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '730',
			) ,
			110 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '463',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '731',
			) ,
			111 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '508',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '732',
			) ,
			112 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '511',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '733',
			) ,
			113 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '464',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '734',
			) ,
			114 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '465',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '735',
			) ,
			115 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '509',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '736',
			) ,
			116 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '466',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '737',
			) ,
			117 => array(
				'parent_id' => '467',
				'field_id' => 38,
				'child_id' => '510',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '738',
			) ,
			118 => array(
				'parent_id' => '650',
				'field_id' => 43,
				'child_id' => '329',
				'order' => '0',
				'grid_field_id' => 135,
				'grid_col_id' => 43,
				'grid_row_id' => '1025',
			) ,
			119 => array(
				'parent_id' => '650',
				'field_id' => 43,
				'child_id' => '241',
				'order' => '0',
				'grid_field_id' => 135,
				'grid_col_id' => 43,
				'grid_row_id' => '1026',
			) ,
			120 => array(
				'parent_id' => '650',
				'field_id' => 43,
				'child_id' => '315',
				'order' => '0',
				'grid_field_id' => 135,
				'grid_col_id' => 43,
				'grid_row_id' => '1027',
			) ,
			121 => array(
				'parent_id' => '650',
				'field_id' => 43,
				'child_id' => '332',
				'order' => '0',
				'grid_field_id' => 135,
				'grid_col_id' => 43,
				'grid_row_id' => '1028',
			) ,
			122 => array(
				'parent_id' => '650',
				'field_id' => 43,
				'child_id' => '304',
				'order' => '0',
				'grid_field_id' => 135,
				'grid_col_id' => 43,
				'grid_row_id' => '1029',
			) ,
			123 => array(
				'parent_id' => '650',
				'field_id' => 43,
				'child_id' => '244',
				'order' => '0',
				'grid_field_id' => 135,
				'grid_col_id' => 43,
				'grid_row_id' => '1030',
			) ,
			124 => array(
				'parent_id' => '650',
				'field_id' => 43,
				'child_id' => '297',
				'order' => '0',
				'grid_field_id' => 135,
				'grid_col_id' => 43,
				'grid_row_id' => '1031',
			) ,
			125 => array(
				'parent_id' => '650',
				'field_id' => 43,
				'child_id' => '235',
				'order' => '0',
				'grid_field_id' => 135,
				'grid_col_id' => 43,
				'grid_row_id' => '1032',
			) ,
			126 => array(
				'parent_id' => '650',
				'field_id' => 43,
				'child_id' => '652',
				'order' => '0',
				'grid_field_id' => 135,
				'grid_col_id' => 43,
				'grid_row_id' => '1033',
			) ,
			127 => array(
				'parent_id' => '650',
				'field_id' => 43,
				'child_id' => '654',
				'order' => '0',
				'grid_field_id' => 135,
				'grid_col_id' => 43,
				'grid_row_id' => '1034',
			) ,
			128 => array(
				'parent_id' => '650',
				'field_id' => 43,
				'child_id' => '656',
				'order' => '0',
				'grid_field_id' => 135,
				'grid_col_id' => 43,
				'grid_row_id' => '1035',
			) ,
			129 => array(
				'parent_id' => '650',
				'field_id' => 43,
				'child_id' => '288',
				'order' => '0',
				'grid_field_id' => 135,
				'grid_col_id' => 43,
				'grid_row_id' => '1036',
			) ,
			130 => array(
				'parent_id' => '800',
				'field_id' => 38,
				'child_id' => '1175',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '1258',
			) ,
			131 => array(
				'parent_id' => '800',
				'field_id' => 38,
				'child_id' => '1176',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '1262',
			) ,
			132 => array(
				'parent_id' => '1021',
				'field_id' => 38,
				'child_id' => '1022',
				'order' => '0',
				'grid_field_id' => 133,
				'grid_col_id' => 38,
				'grid_row_id' => '1867',
			) ,
			133 => array(
				'parent_id' => '359',
				'field_id' => 73,
				'child_id' => '654',
				'order' => '0',
				'grid_field_id' => 146,
				'grid_col_id' => 73,
				'grid_row_id' => '2212',
			) ,
			134 => array(
				'parent_id' => '359',
				'field_id' => 73,
				'child_id' => '626',
				'order' => '1',
				'grid_field_id' => 146,
				'grid_col_id' => 73,
				'grid_row_id' => '2212',
			) ,
			135 => array(
				'parent_id' => '359',
				'field_id' => 73,
				'child_id' => '656',
				'order' => '2',
				'grid_field_id' => 146,
				'grid_col_id' => 73,
				'grid_row_id' => '2212',
			) ,
			136 => array(
				'parent_id' => '359',
				'field_id' => 73,
				'child_id' => '770',
				'order' => '0',
				'grid_field_id' => 146,
				'grid_col_id' => 73,
				'grid_row_id' => '2213',
			) ,
			137 => array(
				'parent_id' => '359',
				'field_id' => 73,
				'child_id' => '628',
				'order' => '1',
				'grid_field_id' => 146,
				'grid_col_id' => 73,
				'grid_row_id' => '2213',
			) ,
		);

		$return[] = array($expected, $data, $matrix_to_grid_fields, $matrix_to_grid_cols, 'Test empty array');

		return $return;
	}
}
